spring:
  config:
    import:
---
spring:
  config:
    activate:
      on-profile: test

---
spring:
  config:
    activate:
      on-profile: local
    import:
      - vault://secret/berapt/iam/common/sandbox
      - vault://secret/berapt/iam/service/sandbox
iam:
  host: http://localhost:8080
---
spring:
  config:
    activate:
      on-profile: sandbox
---
spring:
  config:
    activate:
      on-profile: qa
---
spring:
  config:
    activate:
      on-profile: cbt
---
spring:
  config:
    activate:
      on-profile: prod

