name: Validate PR
on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:      
      matrix:
        application:
          - api/auth
          - api/ggv
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          gradle-version: '8.7'
      - name: Run chmod to make gradlew executable
        run: |
          cd app
          ls -al
          chmod +x ./gradlew
      - name: Build with Gradle
        run: |
          cd app
          ./gradlew build -p :{{ matrix.application }} --build-cache --parallel classe
        # uses: gradle/gradle-build-action@v3
        # with:
        #   arguments: --build-cache -p :{{ matrix.application }} --parallel classes
        #   cache-read-only: false
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: build
    strategy:
      matrix:
        test:
          - api/auth
          - api/ggv
          - application
          - domain
          - external-client
          - infra
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run chmod to make gradlew executable
        run: |
          cd app
          chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: --build-cache --parallel :${{ matrix.test }}:test
          cache-read-only: false






